### ISSUE TITLE
Android build failed for missing keychain_password

### ISSUE THREAD

**Issue by chrisriesgo-bitrise** [bitrise-io/steps-certificate-and-profile-installer#10]
I'm confused about why this build failed. It's an android build, so shouldn't need keychain access. Any ideas? I'm new to bitrise, so I understand I may not be doing things correctly.

``` script
+------------------------------------------------------------------------------+
| (2) certificate-and-profile-installer@1.4.0                                  |
+------------------------------------------------------------------------------+
| id: certificate-and-profile-installer                                        |
| version: 1.4.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-01-18T01:45:27Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
2016/01/18 01:45:30 Input validation failed, err: [!] Missing required input: keychain_password
exit status 1
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | certificate-and-profile-installer@1.4.0 (exit code: 1)       | 3.5 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: .../bitrise-io/steps-certificate-and-profile-installer/issues |
| Source: ...s://github.com/bitrise-io/steps-certificate-and-profile-installer |
+----+--------------------------------------------------------------+----------+
                                          ▼
ERRO[01:45:30] Step (certificate-and-profile-installer@1.4.0) failed, error: (exit status 1) 
+------------------------------------------------------------------------------+
| (3) xamarin-user-management@0.9.1                                            |
+------------------------------------------------------------------------------+
| id: xamarin-user-management                                                  |
| version: 0.9.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-01-18T01:45:31Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
/tmp/bitrise326378401/step_src/step.rb:12:in ``': No such file or directory - /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch (Errno::ENOENT)
	from /tmp/bitrise326378401/step_src/step.rb:12:in `<main>'
ERRO[01:45:31] Step (xamarin-user-management@0.9.1) failed, error: (exit status 1) 
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | xamarin-user-management@0.9.1 (exit code: 1)                 | 0.97 sec |
+----+--------------------------------------------------------------+----------+
| Issue tracker: ...b.com/bitrise-steplib/steps-xamarin-user-management/issues |
| Source: https://github.com/bitrise-steplib/steps-xamarin-user-management     |
+----+--------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment]
The Keychain step is required for iOS apps, to download & activate iOS Certificates & Provisioning Profiles, for Android you need a keystore file and you just have to download it to a location specified in your settings.

**Comment by viktorbenei** [comment]
I'll close this issue, but if you'd still have a problem please let us know!
